### ISSUE TITLE
GeoSPARQL

### ISSUE THREAD

**Issue by akuckartz** [RubenVerborgh/LDflex#18]
I suggest to implement some kind of equivalent to GeoSPARQL.

**Comment by RubenVerborgh** [comment]
If we implement anything, it should be the actual GeoSPARQL spec 🙂 Good suggestion, but it is currently out of scope for this library.

**Comment by rubensworks** [comment]
@akuckartz It would be good to have GeoSPARQL implemented in [Comunica](https://github.com/comunica/comunica) at some point though. Feel free to add your suggestion there.
