### ISSUE TITLE
JSON-LD

### ISSUE THREAD

**Issue by yukulele** [RubenVerborgh/LDflex#26]
Hi Ruben,
We are currently using for our project (Startin'blox) a server that provides data in JSON-LD format.

In the LDFlex examples the requested data is in turtle format.

- Does LDFlex support formats other than turtle?
- How to make LDFlex compatible with JSON-LD?

**Comment by rubensworks** [comment]
Since LDflex uses [Comunica](https://github.com/comunica/comunica) for fetching RDF, the following formats are supported:

* JSON-LD
* TriG
* N-Quads
* Turtle
* N-Triples
* Notation3
* RDF/XML

This list includes JSON-LD, so defining a JSON-LD document as source should already work.

**Comment by sylvainlb** [comment]
Thanks @rubensworks !

For some reason I thought you hadn't activated the support for json-ld. Glad to know it is!

**Comment by RubenVerborgh** [comment]
@rubensworks But did we package it up in https://github.com/RubenVerborgh/LDflex-Comunica though?

**Comment by sylvainlb** [comment]
That is a good question! :D

**Comment by rubensworks** [comment]
Yes, all parsers are included.

LDflex imports this config: https://github.com/RubenVerborgh/LDflex-Comunica/blob/master/config/config-default.json#L13
Which contains a JSON-LD parser here: https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/config/sets/rdf-parsers.json#L18-L22

However, the reason why https://api.test-paris.happy-dev.fr/projects/ is not working here, is because the server is returning a 406 when a more complex accept-header is included.
For example:

```
$ curl -H 'Accept: text/html;application/ld+json' https://api.test-paris.happy-dev.fr/projects/
{"detail":"Could not satisfy the request Accept header.","@context":"https://cdn.happy-dev.fr/owl/hdcontext.jsonld"}
```

**Comment by sylvainlb** [comment]
Oh that's weird. I'll investigate. 
Thanks @rubensworks !

**Comment by sylvainlb** [comment]
Is there a way for us to configure LDflex to accept only one type, while we're working on this multiple type issue?

**Comment by rubensworks** [comment]
You could fork https://github.com/RubenVerborgh/LDflex-Comunica and create your own Comunica config where you delete all RDF parsers except for the JSON-LD parser. By doing this, only the JSON-LD content type would be included in the accept header.

This would be quite a bit of a workaround though, so it may be easier to fix the content negotiation issue on your server :-)

**Comment by sylvainlb** [comment]
Actually @rubensworks media types are to be separated by a comma.

`$ curl -H 'Accept: text/html,application/ld+json' https://api.test-paris.happy-dev.fr/projects/` does return the value

**Comment by rubensworks** [comment]
Oh, silly me...
That's indeed a bug in Comunica, I'll fix it right away.

**Comment by sylvainlb** [comment]
ahah thanks a lot !

**Comment by rubensworks** [comment]
@sylvainlb Fixed in Comunica 1.7.4.

(It is a minor update away from the version that is specified in LDflex-Comunica, so just deleting your lockfile+node_modules and re-installing should give you the fixed Comunica version)

**Comment by yukulele** [comment]
it works! We now get data from our server! thanks!

**Comment by RubenVerborgh** [comment]
Thanks for testing!
