### ISSUE TITLE
Get all predicates of a resource

### ISSUE THREAD

**Issue by yukulele** [RubenVerborgh/LDflex#27]
I need to get all predicates of a resource.

For instance, with the resource in the example (`https://ruben.verborgh.org/profile/#me`), I try:
```javascript
console.log(Object.keys(await person));
```
I expect:
```json5
['name', 'givenName', 'familyName', 'interest', 'friends', /*...*/ ]
```
but I get:
```json5
[ 'settings', 'subject', 'proxy', 'extendPath' ]
```

What is the good way to get all predicates of a resource with LDFlex?

**Comment by RubenVerborgh** [comment]
That would be a good new feature to have; I think @james-martin-jd would like that too.

**Comment by RubenVerborgh** [comment]
Note: the fact that currently the internal properties (`'settings', 'subject', 'proxy', 'extendPath'`) are exposed is due to missing implementation (#28).

Whether or not predicates should be given through `Object.keys` is another matter; we probably want a `.properties` path or so for that.

**Comment by yukulele** [comment]
So right now there's no way to pick them up?

**Comment by RubenVerborgh** [comment]
Indeed, not yet.

**Comment by sylvainlb** [comment]
Thanks @RubenVerborgh !

I think this is a blocker for us to migrate, maybe the last one. Do you think it's a hard thing to do? Would it be something we could contribute to?

**Comment by RubenVerborgh** [comment]
> Do you think it's a hard thing to do?

Not excessively hard; only trouble is that the rest of the code is strongly focused on path queries (so where the object is the variable); here we he'd have a `SELECT DISTINCT` on the predicate instead.

> Would it be something we could contribute to?

You're very welcome to, but it might take quite some time to get familiar with the LDflex code. The external interface it exposes is very simple, meaning all of the complexity is somewhere inside 🙂

I'd expect some work on the SPARQL generation (https://github.com/RubenVerborgh/LDflex/blob/d9893526d39fb16de21bc39d56212708a58befa9/src/SparqlHandler.js#L21), and [wiring up](https://github.com/RubenVerborgh/LDflex/blob/master/src/defaultHandlers.js#L42) a new `\.properties` handler.

I can also look into it, but I'll probably have to postpone my open source work until this summer.

**Comment by sylvainlb** [comment]
Hmmm that means we probably won't be able to migrate to LDFlex before a couple of months.

I'll see if we can find someone to dig into the code in the near future.

**Comment by sylvainlb** [comment]
@RubenVerborgh Fyi @jblemee has been diving into LDFlex and is working on the issue as we speak. He'll probably be back soon with a solution :)

**Comment by yukulele** [comment]
Ok, I can now get predicates list! thanks @jblemee!

@RubenVerborgh the list of predicates returned is in the extended form, is there any way to obtain it in abbreviated form?

what I do:
```js
const predicates = [];
for await (const pred of person.predicates) {
  predicates.push(`${await prd}`);
}
console.log(predicates);
```
what I get:
```js
[
  'http://xmlns.com/foaf/0.1/name',
  'http://xmlns.com/foaf/0.1/givenName',
  'http://xmlns.com/foaf/0.1/familyName',
  'http://xmlns.com/foaf/0.1/interest',
  'http://xmlns.com/foaf/0.1/knows',
  /* … */
]
```
what I wish:
```js
['name', 'givenName', 'familyName', 'interest', 'friends', /* … */ ]
```

**Comment by rubensworks** [comment]
Perhaps it would make sense to let `.predicates` return the expanded IRIs, and `.properties` return the compacted terms?

FYI, the JSON-LD context parser can compact terms like this: https://github.com/rubensworks/jsonld-context-parser.js#compact-an-iri

**Comment by RubenVerborgh** [comment]
Interesting suggestion, I like it!

**Comment by jblemee** [comment]
Like it too, i'll start working on it very soon
