### ISSUE TITLE
What is the signature of object given by promise?

### ISSUE THREAD

**Issue by yukulele** [RubenVerborgh/LDflex#29]
if `person` is a resource,
I can show its name with
```js
console.log((await person.name).toString())
```
but what type of object I get with
```js
console.log(await person.name)
```
?

**Comment by RubenVerborgh** [comment]
It is an LDflex path. They are special objects that can behave like other objects.

So you can do things like:
```javascript
console.log((await person.friends.firstName).toString());
console.log(await (await person.friends).firstName).toString());
```

However, when you `await`, you receive is a _populated_ path that also has a value.

A populated LDflex path conforms to the [RDF/JS `Term` interface](https://rdf.js.org/data-model-spec/#term-interface), so you can treat the returned value as an RDF/JS Term and do things like `.termType`, `.value`, etc.

Plus, it will coerce into a string if you do ``console.log(`#{await person.name}`)``.
