### ISSUE TITLE
Get all subjects in a document

### ISSUE THREAD

**Issue by JordanShurmer** [RubenVerborgh/LDflex#30]
This may already be possible, but I haven't been able to get anything to work.

I'm trying to get all the subjects in a given document, or even all the subjects matching some predicate in a given document.

Example of what I am trying to do:
```js
for await (const activity of data['https://jshurmer.inrupt.net/public/activities']) {
  //activity is now an ldflex object of each activity at that path
}
//or
for await (const bookmark of data['https://jshurmer.inrupt.net/public/bookmarks']) {
 //bookmark is an ldflex of each bookmark
}
//etc.
```

I'd be happy to contribute, if this currently is not supported, but could use a pointer on the best way to introduce this functionality. The sparql handler doesn't seem to to be handling this correctly, it expects a predicate but only has the url as a subject. Could this be fixed with a small change to that handler to support no-predicates? or Would it be better to introduce a new `.all` property that builds a different sparql entirely perhaps?

**Comment by RubenVerborgh** [comment]
It's definitely a good idea to have something for all subjects.

However, the syntax you propose would be inconsistent with the notion of a path, and it already has a meaning: https://solid.github.io/ldflex-playground/#%5B'https%3A%2F%2Fjshurmer.inrupt.net%2Fpublic%2Factivities'%5D

For consistency:
- `data['https://ruben.verborgh.org/profile/#me']` evaluates to `'https://ruben.verborgh.org/profile/#me'`
- `data['https://ruben.verborgh.org/profile/#me'].friends` evaluates to `'https://data.verborgh.org/people/ben_abelshausen'`, etc.
- `data['https://ruben.verborgh.org/profile/#me'].friends.firstName` evaluates to `'Ben'`, etc.

The functionality you suggest could be implemented as, for example, `data['https://jshurmer.inrupt.net/public/activities'].subject`, analogously to #27.
