### ISSUE TITLE
How context in graphs are interpreted?

### ISSUE THREAD

**Issue by matthieu-fesselier** [RubenVerborgh/LDflex#42]
While this request is working fine: https://solid.github.io/ldflex-playground/#%5B'https%3A%2F%2Fapi.coopstarter.happy-dev.fr%2Fformats%2F'%5D.ldp_contains%5B'rdfs%3Alabel'%5D

This one is not: https://solid.github.io/ldflex-playground/#%5B'https%3A%2F%2Fapi.coopstarter.happy-dev.fr%2Fresources%2F'%5D.ldp_contains%5B'rdfs%3Alabel'%5D

It seems to be link to contexts.
In the second container, we add a `@context` property for each resource, to extend the global context.

It is supposed to extend and not to override the global context, right?
Can it be a source of trouble to define the global context is at the end of the document?

**Comment by RubenVerborgh** [comment]
@rubensworks Is that a JSON-LD parsing error?

**Comment by rubensworks** [comment]
Yep, looks like a parsing error indeed, to be investigated...
Reported here: https://github.com/rubensworks/jsonld-streaming-parser.js/issues/33

**Comment by rubensworks** [comment]
Fixed in jsonld-streaming-parser 1.1.2.
Resetting your lockfile and re-installing should give you the latest version.

**Comment by joachimvh** [comment]
This would be in the LDflex-Comunica and query-ldflex packages I assume since this LDflex package has no dependency on jsonld-streaming-parser but those other two do. Anyway, when I remove the lock file and re-install the dependency in the lockfile stays on 1.1.0 so it might require an update of all the other packages that depend on it directly first? @rubensworks

**Comment by rubensworks** [comment]
Oh really? I thought re-installing from no lockfile would pick the latest patch version of packages, but I may be wrong on that. I can't really find any documentation about it atm, but it may be a yarn-only thing.

The proper place to update to the jsonld-streaming-parser dependency would be in @comunica/actor-rdf-parse-jsonld, and then doing a new comunica release (I can do this if you ping me).

**Comment by RubenVerborgh** [comment]
LDflex-Comunica is now on jsonld-streaming-parser 1.1.2 as part of a general update: https://github.com/RubenVerborgh/LDflex-Comunica/commit/a9b62ef5f88a0eb50a7fd2dada408b05da8c32ea

**Comment by RubenVerborgh** [comment]
…and here in 0942d2ddf5e84fd62e27522c1aae259f6c457e85 as well, so I presume this to be fixed. Thanks @matthieu-fesselier, @joachimvh, @rubensworks!
